import { Header } from '~/components/header';

export default function PrivacyPolicy() {
    return (
        <div className="flex min-h-screen flex-col">
            <Header />
            <main className="container mx-auto px-4 py-8">
                <h1 className="mb-6 text-3xl font-bold">
                    Privacy Policy for CampusConnect
                </h1>
                <p className="mb-4">
                    Company: <strong>Campus Connect</strong>
                </p>
                <p className="mb-4">
                    This Privacy Policy describes our policies and procedures on
                    the collection, use, and disclosure of your information when
                    you use the Service and tells you about your privacy rights
                    and how the law protects you.
                </p>
                <p className="mb-4">
                    We use your personal data to provide and improve the
                    Service. By using the Service, you agree to the collection
                    and use of information in accordance with this Privacy
                    Policy.
                </p>

                <h2 className="mb-3 mt-6 text-2xl font-semibold">Support</h2>
                <p className="mb-4">
                    Contact:{' '}
                    <a
                        href="mailto:SUPPORT_EMAIL"
                        className="text-blue-600 hover:underline"
                    >
                        SUPPORT_EMAIL
                    </a>
                </p>

                <h2 className="mb-3 mt-6 text-2xl font-semibold">
                    Interpretation and Definitions
                </h2>
                <ul className="list-disc pl-6">
                    <li>
                        <strong>Account</strong>: a unique account created for
                        you to access our Service or parts of our Service.
                    </li>
                    <li>
                        <strong>Affiliate</strong>: an entity that controls, is
                        controlled by, or is under common control with a party,
                        where &apos;control&apos; means ownership of 50% or more
                        of the shares, equity interest, or other securities
                        entitled to vote for election of directors or other
                        managing authority.
                    </li>
                    <li>
                        <strong>Application</strong>: CampusConnect, the
                        software program provided by the Company.
                    </li>
                    <li>
                        <strong>Company</strong> (referred to as either
                        &apos;the Company&apos;, &apos;We&apos;, &apos;Us&apos;
                        or &apos;Our&apos; in this Agreement): CampusConnect.
                    </li>
                    <li>
                        <strong>Country</strong>: United States.
                    </li>
                    <li>
                        <strong>Device</strong>: any device that can access the
                        Service such as a computer, a cellphone, or a digital
                        tablet.
                    </li>
                    <li>
                        <strong>Personal Data</strong>: any information that
                        relates to an identified or identifiable individual.
                    </li>
                    <li>
                        <strong>Service</strong>: the Application.
                    </li>
                    <li>
                        <strong>Service Provider</strong>: any natural or legal
                        person who processes the data on behalf of the Company.
                        It refers to third-party companies or individuals
                        employed by the Company to facilitate the Service, to
                        provide the Service on behalf of the Company, to perform
                        services related to the Service or to assist the Company
                        in analyzing how the Service is used.
                    </li>
                    <li>
                        <strong>Usage Data</strong>: data collected
                        automatically, either generated by the use of the
                        Service or from the Service infrastructure itself (for
                        example, the duration of a page visit).
                    </li>
                    <li>
                        <strong>You</strong>: the individual accessing or using
                        the Service, or the company, or other legal entity on
                        behalf of which such individual is accessing or using
                        the Service, as applicable.
                    </li>
                </ul>

                <h2 className="mb-3 mt-6 text-2xl font-semibold">
                    Collecting and Using Your Personal Data
                </h2>
                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Types of Data Collected
                </h3>
                <ul className="list-disc pl-6">
                    <li>
                        <strong>Personal Data</strong>: information that can be
                        used to contact or identify you, such as your email
                        address.
                    </li>
                    <li>
                        <strong>Usage Data</strong>: information collected
                        automatically when using the Service, such as your
                        Device&apos;s Internet Protocol address (e.g., IP
                        address), browser type, browser version, the pages of
                        our Service that you visit, the time and date of your
                        visit, the time spent on those pages, unique device
                        identifiers, and other diagnostic data.
                    </li>
                </ul>

                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Information Collected while Using the Application
                </h3>
                <p className="mb-4">
                    User email, name, profile image, and a unique ID. This
                    information is stored and shared with our analytics platform
                    Google Analytics in order to help improve the experience of
                    the app.
                </p>

                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Use of Your Personal Data
                </h3>
                <p className="mb-4">
                    We may use your Personal Data for the following purposes:
                </p>
                <ul className="list-disc pl-6">
                    <li>
                        To provide and maintain our Service, including to
                        monitor the usage of our Service.
                    </li>
                    <li>
                        To manage your Account: to manage your registration as a
                        user of the Service. The Personal Data you provide can
                        give you access to different functionalities of the
                        Service that are available to you as a registered user.
                    </li>
                    <li>
                        For the performance of a contract: the development,
                        compliance, and undertaking of the purchase contract for
                        the products, items, or services you have purchased or
                        of any other contract with Us through the Service.
                    </li>
                    <li>
                        To contact you: to contact you by email, telephone
                        calls, SMS, or other equivalent forms of electronic
                        communication, such as a mobile application&apos;s push
                        notifications regarding updates or informative
                        communications related to the functionalities, products,
                        or contracted services, including the security updates,
                        when necessary or reasonable for their implementation.
                    </li>
                    <li>
                        To provide you with news, special offers, and general
                        information about other goods, services, and events
                        which we offer that are similar to those that you have
                        already purchased or enquired about unless you have
                        opted not to receive such information.
                    </li>
                    <li>
                        To manage your requests: to attend and manage your
                        requests to Us.
                    </li>
                    <li>
                        For business transfers: We may use your information to
                        evaluate or conduct a merger, divestiture,
                        restructuring, reorganization, dissolution, or other
                        sale or transfer of some or all of Our assets, whether
                        as a going concern or as part of bankruptcy,
                        liquidation, or similar proceeding, in which Personal
                        Data held by Us about our Service users is among the
                        assets transferred.
                    </li>
                    <li>
                        For other purposes: We may use your information for
                        other purposes, such as data analysis, identifying usage
                        trends, determining the effectiveness of our promotional
                        campaigns, and evaluating and improving our Service,
                        products, services, marketing, and your experience.
                    </li>
                </ul>

                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Sharing Your Personal Data
                </h3>
                <ul className="list-disc pl-6">
                    <li>
                        With Service Providers: We may share your personal
                        information with Service Providers to monitor and
                        analyze the use of our Service, to contact you.
                    </li>
                    <li>
                        For business transfers: We may share or transfer your
                        personal information in connection with, or during
                        negotiations of, any merger, sale of Company assets,
                        financing, or acquisition of all or a portion of Our
                        business to another company.
                    </li>
                    <li>
                        With Affiliates: We may share your information with Our
                        affiliates, in which case we will require those
                        affiliates to honor this Privacy Policy. Affiliates
                        include Our parent company and any other subsidiaries,
                        joint venture partners, or other companies that We
                        control or that are under common control with Us.
                    </li>
                    <li>
                        With business partners: We may share your information
                        with Our business partners to offer you certain
                        products, services, or promotions.
                    </li>
                    <li>
                        With other users: when you share personal information or
                        otherwise interact in the public areas with other users,
                        such information may be viewed by all users and may be
                        publicly distributed outside.
                    </li>
                    <li>
                        With Your consent: We may disclose your personal
                        information for any other purpose with your consent.
                    </li>
                </ul>

                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Retention of Your Personal Data
                </h3>
                <p className="mb-4">
                    We will retain your Personal Data only for as long as is
                    necessary for the purposes set out in this Privacy Policy.
                    We will retain and use your Personal Data to the extent
                    necessary to comply with our legal obligations (for example,
                    if we are required to retain your data to comply with
                    applicable laws), resolve disputes, and enforce our legal
                    agreements and policies. We will also retain Usage Data for
                    internal analysis purposes. Usage Data is generally retained
                    for a shorter period of time, except when this data is used
                    to strengthen the security or to improve the functionality
                    of Our Service, or We are legally obligated to retain this
                    data for longer time periods.
                </p>

                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Transfer of Your Personal Data
                </h3>
                <p className="mb-4">
                    Your information, including Personal Data, is processed at
                    the Company&apos;s operating offices and in any other places
                    where the parties involved in the processing are located. It
                    means that this information may be transferred to — and
                    maintained on — computers located outside of your state,
                    province, country, or other governmental jurisdiction where
                    the data protection laws may differ than those from your
                    jurisdiction. Your consent to this Privacy Policy followed
                    by your submission of such information represents your
                    agreement to that transfer. We will take all steps
                    reasonably necessary to ensure that your data is treated
                    securely and in accordance with this Privacy Policy, and no
                    transfer of your Personal Data will take place to an
                    organization or a country unless there are adequate controls
                    in place including the security of your data and other
                    personal information.
                </p>

                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Delete Your Personal Data
                </h3>
                <p className="mb-4">
                    You have the right to delete or request that We assist in
                    deleting the Personal Data that We have collected about you.
                    Our Service may give you the ability to delete certain
                    information about you from within the Service. You may
                    update, amend, or delete your information at any time by
                    signing in to your Account, if you have one, and visiting
                    the account settings section that allows you to manage your
                    personal information. You may also contact Us to request
                    access to, correct, or delete any personal information that
                    You have provided to Us. Please note, however, that We may
                    need to retain certain information when We have a legal
                    obligation or lawful basis to do so.
                </p>

                <h3 className="mb-2 mt-4 text-xl font-semibold">
                    Disclosure of Your Personal Data
                </h3>
                <p className="mb-4">
                    Business Transactions If the Company is involved in a
                    merger, acquisition, or asset sale, your Personal Data may
                    be transferred. We will provide notice before your Personal
                    Data is transferred and becomes subject to a different
                    Privacy Policy. Law enforcement Under certain circumstances,
                    the Company may be required to disclose your Personal Data
                    if required to do so by law or in response to valid requests
                    by public authorities (e.g., a court or a government
                    agency). Other legal requirements The Company may disclose
                    your Personal Data in the good faith belief that such action
                    is necessary to:
                </p>
                <ul className="list-disc pl-6">
                    <li>Comply with a legal obligation</li>
                    <li>
                        Protect and defend the rights or property of the Company
                    </li>
                    <li>Prevent or investigate possible</li>
                </ul>

                <h2 className="mb-3 mt-6 text-2xl font-semibold">Contact Us</h2>
                <p className="mb-4">
                    If you have any questions about this Privacy Policy, you can
                    contact us:
                </p>
                <ul className="list-disc pl-6">
                    <li>
                        By email:{' '}
                        <a
                            href="mailto:CONTACT_EMAIL"
                            className="text-blue-600 hover:underline"
                        >
                            CONTACT_EMAIL
                        </a>
                    </li>
                </ul>

                <h2 className="mb-3 mt-6 text-2xl font-semibold">
                    To Delete Your Account
                </h2>
                <p>In order to delete your account:</p>
                <ol className="list-decimal pl-6">
                    <li>
                        Email{' '}
                        <a
                            href="mailto:CONTACT_EMAIL"
                            className="text-blue-600 hover:underline"
                        >
                            CONTACT_EMAIL
                        </a>{' '}
                        with the subject line: &quot;delete account&quot;. In
                        the body of your email, make sure to send us the email
                        you signed up with.
                    </li>
                    <li>Log out of the app</li>
                    <li>
                        Your account will then be deleted within 24 hours by our
                        team
                    </li>
                </ol>
            </main>
        </div>
    );
}
